/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package words.View;

import java.awt.Button;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JPanel;
import words.Line;
import words.Word;

/**
 *
 * @author iworourke
 */
public class LineJPanel extends JPanel {

    private Line line;
    private ArrayList<WordJPanel> wordPanels;
    private ArrayList<JButton> buttons;
    
    /**
     * Creates new form LineJPanel
     */
    public LineJPanel() {
        initComponents();
        
        /*buttons = new ArrayList<>();
        
        for (int i = 0; i < 3; i++) {
            buttons.add(new JButton("button" + i));
        }
        
        setLayout(new GridLayout(1,1));
        
        for (JButton b : buttons) {
            add(b);
        }*/
        
        line = new Line();
        wordPanels = new ArrayList<>();
        
        for (int i = 0; i < 3; i++) {
            wordPanels.add(new WordJPanel());
        }
        
        setLayout(new GridLayout(1, 1, 5, 5));
        
        for (WordJPanel w : wordPanels) {
            add(w);
        }
        
        revalidate();
        repaint();
    }
    
    public LineJPanel(Line l) {
        initComponents();
        setPreferredSize(getPreferredSize());
        /*buttons = new ArrayList<>();
        
        for (int i = 0; i < 3; i++) {
            buttons.add(new JButton("button" + i));
        }
        
        setLayout(new GridLayout(1,1));
        
        for (JButton b : buttons) {
            add(b);
        }*/
        
        wordPanels = new ArrayList<>();
        line = new Line(l);
        ArrayList<Word> wordList = line.getWords();
        
        for (Word w : wordList) {
            wordPanels.add(new WordJPanel(w));
        }
        
        setLayout(new GridLayout(1, 1, 5, 5));
        
        for (WordJPanel w : wordPanels) {
            add(w);
        }
        
        revalidate();
        repaint();   
    }
    
    @Override
    public Dimension getPreferredSize() {
        return new Dimension(820, 70);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 102, 255));
        setPreferredSize(new java.awt.Dimension(820, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
