/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package words.View;

import java.awt.Dimension;
import javax.swing.JFrame;
import words.Word;

/**
 *
 * @author iworourke
 */
public class WordJPanel extends javax.swing.JPanel {

    private Word word;
    
    /**
     * Creates new form WordJPanel
     */
    public WordJPanel() {
        initComponents();
        word = new Word();
        
        revalidate();
        repaint();
    }
    
    public WordJPanel(Word w) {
        initComponents();
        setPreferredSize(getPreferredSize());
        
        word = new Word(w);
        
        if (word != null) {
            String conventionalSpelling = word.getConventionalSpelling();
            String phoneticSpelling = word.getPhoneticText();
        
            conventionalTextBox.setText(conventionalSpelling);
            phoneticTextBox.setText(phoneticSpelling);
        }
        else {
            conventionalTextBox.setText("Null Word!");
            phoneticTextBox.setText("Null Word!");
        }
        
        revalidate();
        repaint();
    }
    
    
    @Override
    public Dimension getPreferredSize() {
        return new Dimension(350, 60);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conventionalTextBox = new javax.swing.JTextField();
        phoneticTextBox = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(350, 60));

        conventionalTextBox.setName("conventionalSpelling_TextField"); // NOI18N

        phoneticTextBox.setName("phoneticSpelling_TextField"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(conventionalTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
            .addComponent(phoneticTextBox)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(conventionalTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneticTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        conventionalTextBox.getAccessibleContext().setAccessibleName("conventionalSpelling_TextField");
        phoneticTextBox.getAccessibleContext().setAccessibleName("phoneticSpelling_TextField");
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField conventionalTextBox;
    private javax.swing.JTextField phoneticTextBox;
    // End of variables declaration//GEN-END:variables

}
